# Generated by Django 4.1.7 on 2023-04-19 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_history_cb',
            fields=[
                ('loan_historycb_id', models.AutoField(primary_key=True, serialize=False)),
                ('inquiery', models.CharField(max_length=255, verbose_name='Запрос')),
                ('Inquiery_last_request_to_our_FCU', models.DateField(verbose_name='последний запрос нашему ФКУ')),
                ('count_requet', models.IntegerField(verbose_name='количество запросов')),
                ('count_of_delinquencies_on_active_loans', models.IntegerField(verbose_name='кол-во просрочек по активным кредитам')),
                ('max_current_arrears', models.IntegerField(verbose_name='макс текущ просрочка ')),
                ('max_current_arrears_year', models.IntegerField(verbose_name='макс просрочка в год')),
                ('count_loan_invarious_FCUs', models.IntegerField(verbose_name='кол-во кредитов в различных ФКУ')),
                ('total_number_of_pledges', models.IntegerField(verbose_name='суммарное кол-во запросов')),
                ('count_of_connected_subjects', models.IntegerField(verbose_name='кол-во связанных субьектов')),
                ('count_of_active_disputes', models.IntegerField(verbose_name='кол-во активных споров')),
                ('count_of_close_disputes', models.IntegerField(verbose_name='кол-во закрытых споров')),
                ('count_of_requests_per_month', models.IntegerField(verbose_name='кол-во запросов за месяц')),
                ('count_of_requests_in3months', models.IntegerField(verbose_name='кол-во запросов за 3 месяца')),
                ('count_of_requests_in6months', models.IntegerField(verbose_name='кол-во запросов за 6 месяца')),
                ('count_of_requests_in12months', models.IntegerField(verbose_name='кол-во запросов за 12 месяца')),
                ('count_of_requests_in24months', models.IntegerField(verbose_name='кол-во запросов за 24 месяца')),
            ],
            options={
                'verbose_name': 'Кредитная история с киба',
                'verbose_name_plural': 'Кредитные истории с киба',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=256, verbose_name='Результат')),
                ('reason', models.CharField(max_length=256, verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.CreateModel(
            name='Inquery',
            fields=[
                ('inquery_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField(verbose_name='Дата запроса')),
                ('sector', models.CharField(max_length=256, verbose_name='Сектор')),
                ('reason', models.CharField(max_length=256, verbose_name='Причина')),
                ('belonging_to_the_current_FCU', models.IntegerField(verbose_name='Принадлежность к ФКУ')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Inqueries', to='loan_history_cb.result')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
        migrations.CreateModel(
            name='CreditBeuro',
            fields=[
                ('cb_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_credit', models.CharField(max_length=256, verbose_name='Вид кредита')),
                ('purpose_of_funding', models.CharField(max_length=256, verbose_name='Цель финансирования')),
                ('currency_of_the_loan', models.CharField(max_length=64, verbose_name='Валюта кредита')),
                ('type_of_payment', models.CharField(max_length=128, verbose_name='Тип платежа')),
                ('subtypeofcredit', models.CharField(max_length=128, verbose_name='Подвид платежа')),
                ('loan_Stage', models.CharField(max_length=128, verbose_name='Стадия кредита')),
                ('loan_status', models.CharField(max_length=128, verbose_name='Статус кредита')),
                ('lender', models.CharField(max_length=128, verbose_name='Кредитор')),
                ('Loan_recipient', models.CharField(max_length=258, verbose_name='Получатель кредита')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('last_upd_date', models.DateField(verbose_name='Последнее обновление')),
                ('next_payment_date', models.DateField(verbose_name='След дата платежа')),
                ('date_of_restructuring', models.DateField(verbose_name='Дата реструктуризации')),
                ('contract_end_date', models.DateField(verbose_name='Дата окончания по договору')),
                ('actual_date_of_credit', models.DateField(verbose_name='Фактич дата погашения')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общ сумма')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа ')),
                ('total_loan_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общ сумма кредита')),
                ('frequency_of_payments', models.CharField(max_length=64, verbose_name='Периодичность платежей')),
                ('count_of_payments', models.IntegerField(verbose_name='кол-во платежей')),
                ('main_amount_owed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Осн сумма задолженности')),
                ('amount_monthly_payments', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма месячных платежей')),
                ('Interest_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='остаток по процентам')),
                ('amount_written_off', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Списанная сумма')),
                ('amount_of_prolongation', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма пролонгации')),
                ('amount_of_additional_fees', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма доп сборов')),
                ('additional_fees_written_off', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Списанные доп сборы')),
                ('interest_deducted_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Списанная сумма по процентам')),
                ('prolongation_date', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='дата пролонгации')),
                ('amount_of_delay', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма просрочки')),
                ('overdue_interest', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='просроченные проценты')),
                ('days_in_arrears', models.IntegerField(verbose_name='дни просрочки')),
                ('count_of_delay', models.IntegerField(verbose_name='кол-во просрочек')),
                ('loah_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CreditBeuro', to='loan_history_cb.loan_history_cb')),
            ],
            options={
                'verbose_name': 'Кредитное бюро',
                'verbose_name_plural': 'Кредитные бюро',
            },
        ),
    ]
