# Generated by Django 4.1.7 on 2023-05-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('fatherstname', models.CharField(max_length=64, verbose_name='Отчество')),
                ('dateofbirth', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=16)),
                ('сitizenship', models.CharField(max_length=155, verbose_name='Гражданство')),
                ('inn', models.CharField(max_length=64, verbose_name='ИНН')),
                ('document_number', models.CharField(max_length=64, verbose_name='Номер документа')),
                ('expiration_date', models.DateField(verbose_name='срок действия')),
                ('date_of_issue', models.DateField(verbose_name='дата выдачи')),
                ('distribution_organization', models.CharField(max_length=256, verbose_name='орган выдачи')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('Occupation', models.CharField(max_length=256, verbose_name='Род деятельности')),
                ('family_status', models.CharField(max_length=256, verbose_name='Семейное положение')),
                ('contact', models.CharField(max_length=256, verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
