# Generated by Django 4.1.7 on 2023-05-16 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='loan_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_lh', to='loan.loan_history'),
        ),
    ]
