# Generated by Django 4.1.7 on 2023-04-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bail',
            options={'verbose_name': 'Залог', 'verbose_name_plural': 'Залоги'},
        ),
        migrations.AlterModelOptions(
            name='bail_type',
            options={'verbose_name': 'Тип залога', 'verbose_name_plural': 'Типы залогов'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': 'Кредит', 'verbose_name_plural': 'Кредиты'},
        ),
        migrations.AlterModelOptions(
            name='loan_history',
            options={'verbose_name': 'Кредитная история', 'verbose_name_plural': 'Кредитные истории'},
        ),
        migrations.AlterModelOptions(
            name='repayment_schedule',
            options={'verbose_name': 'Календарь погашений', 'verbose_name_plural': 'Календари погашений'},
        ),
    ]
